# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
pandoc_version: 1.19.2.1
r_github_packages:
  - r-lib/covr
addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libxml2-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - libgs-dev
      - qpdf
      - ghostscript

script:
- R CMD build . --compact-vignettes=gs+qpdf
- xvfb-run R CMD check *tar.gz --as-cran
 
after_success:
  - xvfb-run Rscript -e 'covr::coveralls(type=c("vignettes","tests","examples"))'
 
