# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
pandoc_version: 1.19.2.1
addons:
  apt:
    packages:
      - libxml2-dev